### ISSUE TITLE
Class "object" not found

### ISSUE THREAD

**Issue by Faxendo** [ImoucheG/GeoRide-Jeedom#2]
Hello there,

I get the following error on plugin page after install and API key set :

`Class "object" not found`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10961243/71977277-aa8a0f80-3218-11ea-989e-5d5a49aa27b1.png">

Where does this error can come from ?

My actual version of Jeedom : 4.0.37

Thanks for your help :)

**Comment by ImoucheG** [comment]
Hello,
I can see you use Freebox delta, this system is based on Jeedom V4, he is in beta for moment.
I push a fix for this version (v4), he must worked now :)
You can follow the development at https://github.com/ImoucheG/GeoRide-Jeedom-Source.
Update your plugin since your Jeedom interface :) GeoRide v1.0.3.
Cordially,
ImoucheG

**Comment by Faxendo** [comment]
Very good, everything's ok now 😄 

Thanks for fast support ! Do you have a list of next features you're planning to release/develop ?

**Comment by ImoucheG** [comment]
For mobility I must develop the widget of GeoRide-Jeedom for Jeedom mobile app.
Do you have features suggestions ? :)

**Comment by Faxendo** [comment]
I don't know yet all Jeedom's capabilities, but I thought about using GeoRide's websocket connection to provide (nearly) instant updates, instead of using crons :)
